# Домашнее задание №7

1. Выбрать по 6 предсказаний для пользователей
2. Удалить фейковый элемент
3. Оставить 5 остортированных предсказаний для каждого пользователя
4. Посчитать метрику (map@5, precision@5)

Определите сильно ли отличается качество ALS из implicit и pyspark, сравнивайте по метрикам map@5, precision@5

In [1]:
import pandas as pd
import numpy as np

from pyspark.ml.recommendation import ALS
from pyspark.sql import SparkSession
from pyspark.sql.types import DoubleType
import pyspark.sql.functions as sf

# Для работы с матрицами
from scipy.sparse import csr_matrix, coo_matrix

# Матричная факторизация
from implicit.als import AlternatingLeastSquares
from implicit.nearest_neighbours import bm25_weight, tfidf_weight


# Функции из 1-ого вебинара
import os, sys

module_path = os.path.abspath(os.path.join(os.pardir))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from best_rec_lib.metrics import precision_at_k, ap_k, recall_at_k
from best_rec_lib.utils import prefilter_items

import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv('../retail_train.csv')
item_features = pd.read_csv('../product.csv')
user_features = pd.read_csv('../hh_demographic.csv')

# column processing
item_features.columns = [col.lower() for col in item_features.columns]
user_features.columns = [col.lower() for col in user_features.columns]

item_features.rename(columns={'product_id': 'item_id'}, inplace=True)
user_features.rename(columns={'household_key': 'user_id'}, inplace=True)

# train test split
test_size_weeks = 3

data_train = data[data['week_no'] < data['week_no'].max() - test_size_weeks]
data_test = data[data['week_no'] >= data['week_no'].max() - test_size_weeks]

data_train.head(2)

,user_id,basket_id,day,item_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc
0,2375,26984851472,1,1004906,1,1.39,364,-0.6,1631,1,0.0,0.0
1,2375,26984851472,1,1033142,1,0.82,364,0.0,1631,1,0.0,0.0

In [3]:
n_items_before = data_train['item_id'].nunique()

data_train = prefilter_items(data_train, 5000, item_features)

n_items_after = data_train['item_id'].nunique()
print('Decreased # items from {} to {}'.format(n_items_before, n_items_after))

Decreased # items from 86865 to 5001

In [4]:
user_item_matrix = pd.pivot_table(data_train, 
                                  index='user_id', columns='item_id', 
                                  values='quantity', # Можно пробоват ьдругие варианты
                                  aggfunc='count', 
                                  fill_value=0
                                 )

user_item_matrix = user_item_matrix.astype(float) # необходимый тип матрицы для implicit

# переведем в формат saprse matrix
sparse_user_item = csr_matrix(user_item_matrix).tocsr()

user_item_matrix.head(2)

item_id,117847,279994,818981,819255,819308,819400,819487,819590,819594,819840,...,15926775,15926844,15926886,15972074,15972298,15972565,15972790,16100266,16729299,16729415
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
data_test = data_test[data_test['item_id'].isin(data_train['item_id'].unique())]

In [6]:
result = data_test.groupby('user_id')['item_id'].unique().reset_index()
result.columns=['user_id', 'actual']
result.head(2)

   user_id                                             actual
0        1  [856942, 865456, 951954, 971585, 979707, 99065...
1        3                                           [920626]

In [7]:
userids = user_item_matrix.index.values
itemids = user_item_matrix.columns.values

matrix_userids = np.arange(len(userids))
matrix_itemids = np.arange(len(itemids))

id_to_itemid = dict(zip(matrix_itemids, itemids))
id_to_userid = dict(zip(matrix_userids, userids))

itemid_to_id = dict(zip(itemids, matrix_itemids))
userid_to_id = dict(zip(userids, matrix_userids))

##### Spark

In [8]:
session = (SparkSession.builder.config('spark.executor.memory', "1500mb")
    .config("spark.sql.shuffle.partitions", "100")
    .config("spark.driver.bindAddress", "127.0.0.1")
    .config("spark.driver.host", "localhost")
    .config('spark.executor.instances', 4)
    .config('spark.executor.cores', 4)
    .config("spark.sql.execution.arrow.pyspark.enabled", "true")
    .master("local[*]")
    .enableHiveSupport()
    .getOrCreate()
    )

In [9]:
session

In [11]:
df_to_spark = data_train[["user_id", "item_id", "quantity"]]

In [12]:
spark_data_train = session.createDataFrame(df_to_spark)

In [13]:
spark_data_train = spark_data_train.withColumnRenamed("quantity", "relevance")

In [14]:
def get_recommendations_spark(df, N=5):
    spam = list(df.item_id)
    if 999999 in spam:
        spam.remove(999999)
    
    return spam[:N]

In [15]:
def als_spark(prec_met, map_met, result, spark_data_train, factors, reg_st, iterations, alpha, N=5):
    i = 1
    for fact in factors:
        for reg in reg_st:
            for itrn in iterations:
                for alp in alpha:
                    
                    print(f'{i}/{len(factors)*len(reg_st)*len(iterations)*len(alpha)}', fact, reg, itrn, alp)

                    model = ALS(rank=fact, 
                                userCol="user_id",
                                itemCol="item_id", 
                                ratingCol="relevance", 
                                implicitPrefs=True, # тип ALS
                                coldStartStrategy="drop",
                                maxIter=itrn, 
                                alpha=alp, 
                                regParam=reg,
                                seed=42
                    ).fit(spark_data_train)

                    # предсказания для всех пользователей
                    recs_als = model.recommendForAllUsers(6)

                    # Разворачиваем рекомендации через функцию explode
                    recs_als = (recs_als
                                .withColumn("recommendations", sf.explode("recommendations"))
                                .withColumn("item_id", sf.col("recommendations.item_id"))
                                .withColumn("relevance", sf.col("recommendations.rating").cast(DoubleType()),)
                                .select("user_id", "item_id", "relevance")
                        )

                    recs_als = recs_als.toPandas()
                    users = list(set(recs_als.user_id))
                    new_test_users = set(result['user_id']) - set(users)
                    
                    if new_test_users:
                        result = result[~result['user_id'].isin(new_test_users)]


                    result[f'als_spark_{fact}_{reg}_{alp}_{itrn}'] = result['user_id'].map(lambda x: get_recommendations_spark(recs_als.loc[recs_als['user_id'] == x], N))
                    prec_met[f'als_spark_{fact}_{reg}_{alp}_{itrn}'] = result.apply(lambda row: precision_at_k(row[f'als_spark_{fact}_{reg}_{alp}_{itrn}'], row['actual']), axis=1).mean()
                    map_met[f'als_spark_{fact}_{reg}_{alp}_{itrn}'] = result.apply(lambda row: ap_k(row[f'als_spark_{fact}_{reg}_{alp}_{itrn}'], row['actual']), axis=1).mean()
                    
                    i += 1
                    
    return result, prec_met, map_met

In [16]:
# Словари метрик
prec_met = dict()
map_met = dict()

# Списки гиперпараметров для моделей
factors = [50, 150, 200, 250, 300, 350]
reg_st = [0.005, 0.01, 0.03, 0.05]
alpha = [0.25, 0.5, 1.0, 1.25, 1.5]
iterations = [1, 2, 3, 5, 8, 10]

In [17]:
%%time
result, prec_met, map_met = als_spark(prec_met, map_met, result, spark_data_train, factors, reg_st, iterations, alpha, N=5)

1/720 50 0.005 1 0.25
2/720 50 0.005 1 0.5
3/720 50 0.005 1 1.0
4/720 50 0.005 1 1.25
5/720 50 0.005 1 1.5
6/720 50 0.005 2 0.25
7/720 50 0.005 2 0.5
8/720 50 0.005 2 1.0
9/720 50 0.005 2 1.25
10/720 50 0.005 2 1.5
11/720 50 0.005 3 0.25
12/720 50 0.005 3 0.5
13/720 50 0.005 3 1.0
14/720 50 0.005 3 1.25
15/720 50 0.005 3 1.5
16/720 50 0.005 5 0.25
17/720 50 0.005 5 0.5
18/720 50 0.005 5 1.0
19/720 50 0.005 5 1.25
20/720 50 0.005 5 1.5
21/720 50 0.005 8 0.25
22/720 50 0.005 8 0.5
23/720 50 0.005 8 1.0
24/720 50 0.005 8 1.25
25/720 50 0.005 8 1.5
26/720 50 0.005 10 0.25
27/720 50 0.005 10 0.5
28/720 50 0.005 10 1.0
29/720 50 0.005 10 1.25
30/720 50 0.005 10 1.5
31/720 50 0.01 1 0.25
32/720 50 0.01 1 0.5
33/720 50 0.01 1 1.0
34/720 50 0.01 1 1.25
35/720 50 0.01 1 1.5
36/720 50 0.01 2 0.25
37/720 50 0.01 2 0.5
38/720 50 0.01 2 1.0
39/720 50 0.01 2 1.25
40/720 50 0.01 2 1.5
41/720 50 0.01 3 0.25
42/720 50 0.01 3 0.5
43/720 50 0.01 3 1.0
44/720 50 0.01 3 1.25
45/720 50 0.01 3 1.5
46/720 50 0.01 5 0.25
47/720 50 0.01 5 0.5
48/720 50 0.01 5 1.0
49/720 50 0.01 5 1.25
50/720 50 0.01 5 1.5
51/720 50 0.01 8 0.25
52/720 50 0.01 8 0.5
53/720 50 0.01 8 1.0
54/720 50 0.01 8 1.25
55/720 50 0.01 8 1.5
56/720 50 0.01 10 0.25
57/720 50 0.01 10 0.5
58/720 50 0.01 10 1.0
59/720 50 0.01 10 1.25
60/720 50 0.01 10 1.5
61/720 50 0.03 1 0.25
62/720 50 0.03 1 0.5
63/720 50 0.03 1 1.0
64/720 50 0.03 1 1.25
65/720 50 0.03 1 1.5
66/720 50 0.03 2 0.25
67/720 50 0.03 2 0.5
68/720 50 0.03 2 1.0
69/720 50 0.03 2 1.25
70/720 50 0.03 2 1.5
71/720 50 0.03 3 0.25
72/720 50 0.03 3 0.5
73/720 50 0.03 3 1.0
74/720 50 0.03 3 1.25
75/720 50 0.03 3 1.5
76/720 50 0.03 5 0.25
77/720 50 0.03 5 0.5
78/720 50 0.03 5 1.0
79/720 50 0.03 5 1.25
80/720 50 0.03 5 1.5
81/720 50 0.03 8 0.25
82/720 50 0.03 8 0.5
83/720 50 0.03 8 1.0
84/720 50 0.03 8 1.25
85/720 50 0.03 8 1.5
86/720 50 0.03 10 0.25
87/720 50 0.03 10 0.5
88/720 50 0.03 10 1.0
89/720 50 0.03 10 1.25
90/720 50 0.03 10 1.5
91/720 50 0.05 1 0.25
92/720 50 0.05 1 0.5
93/720 50 0.05 1 1.0
94/720 50 0.05 1 1.25
95/720 50 0.05 1 1.5
96/720 50 0.05 2 0.25
97/720 50 0.05 2 0.5
98/720 50 0.05 2 1.0
99/720 50 0.05 2 1.25
100/720 50 0.05 2 1.5
101/720 50 0.05 3 0.25
102/720 50 0.05 3 0.5
103/720 50 0.05 3 1.0
104/720 50 0.05 3 1.25
105/720 50 0.05 3 1.5
106/720 50 0.05 5 0.25
107/720 50 0.05 5 0.5
108/720 50 0.05 5 1.0
109/720 50 0.05 5 1.25
110/720 50 0.05 5 1.5
111/720 50 0.05 8 0.25
112/720 50 0.05 8 0.5
113/720 50 0.05 8 1.0
114/720 50 0.05 8 1.25
115/720 50 0.05 8 1.5
116/720 50 0.05 10 0.25
117/720 50 0.05 10 0.5
118/720 50 0.05 10 1.0
119/720 50 0.05 10 1.25
120/720 50 0.05 10 1.5
121/720 150 0.005 1 0.25
122/720 150 0.005 1 0.5
123/720 150 0.005 1 1.0
124/720 150 0.005 1 1.25
125/720 150 0.005 1 1.5
126/720 150 0.005 2 0.25
127/720 150 0.005 2 0.5
128/720 150 0.005 2 1.0
129/720 150 0.005 2 1.25
130/720 150 0.005 2 1.5
131/720 150 0.005 3 0.25
132/720 150 0.005 3 0.5
133/720 150 0.005 3 1.0
134/720 150 0.005 3 1.25
135/720 150 0.005 3 1.5
136/720 150 0.005 5 0.25
137/720 150 0.005 5 0.5
138/720 150 0.005 5 1.0
139/720 150 0.005 5 1.25
140/720 150 0.005 5 1.5
141/720 150 0.005 8 0.25
142/720 150 0.005 8 0.5
143/720 150 0.005 8 1.0
144/720 150 0.005 8 1.25
145/720 150 0.005 8 1.5
146/720 150 0.005 10 0.25
147/720 150 0.005 10 0.5
148/720 150 0.005 10 1.0
149/720 150 0.005 10 1.25
150/720 150 0.005 10 1.5
151/720 150 0.01 1 0.25
152/720 150 0.01 1 0.5
153/720 150 0.01 1 1.0
154/720 150 0.01 1 1.25
155/720 150 0.01 1 1.5
156/720 150 0.01 2 0.25
157/720 150 0.01 2 0.5
158/720 150 0.01 2 1.0
159/720 150 0.01 2 1.25
160/720 150 0.01 2 1.5
161/720 150 0.01 3 0.25
162/720 150 0.01 3 0.5
163/720 150 0.01 3 1.0
164/720 150 0.01 3 1.25
165/720 150 0.01 3 1.5
166/720 150 0.01 5 0.25
167/720 150 0.01 5 0.5
168/720 150 0.01 5 1.0
169/720 150 0.01 5 1.25
170/720 150 0.01 5 1.5
171/720 150 0.01 8 0.25
172/720 150 0.01 8 0.5
173/720 150 0.01 8 1.0
174/720 150 0.01 8 1.25
175/720 150 0.01 8 1.5
176/720 150 0.01 10 0.25
177/720 150 0.01 10 0.5
178/720 150 0.01 10 1.0
179/720 150 0.01 10 1.25
180/720 150 0.01 10 1.5
181/720 150 0.03 1 0.25
182/720 150 0.03 1 0.5
183/720 150 0.03 1 1.0
184/720 150 0.03 1 1.25
185/720 150 0.03 1 1.5
186/720 150 0.03 2 0.25
187/720 150 0.03 2 0.5
188/720 150 0.03 2 1.0
189/720 150 0.03 2 1.25
190/720 150 0.03 2 1.5
191/720 150 0.03 3 0.25
192/720 150 0.03 3 0.5
193/720 150 0.03 3 1.0
194/720 150 0.03 3 1.25
195/720 150 0.03 3 1.5
196/720 150 0.03 5 0.25
197/720 150 0.03 5 0.5
198/720 150 0.03 5 1.0
199/720 150 0.03 5 1.25
200/720 150 0.03 5 1.5
201/720 150 0.03 8 0.25
202/720 150 0.03 8 0.5
203/720 150 0.03 8 1.0
204/720 150 0.03 8 1.25
205/720 150 0.03 8 1.5
206/720 150 0.03 10 0.25
207/720 150 0.03 10 0.5
208/720 150 0.03 10 1.0
209/720 150 0.03 10 1.25
210/720 150 0.03 10 1.5
211/720 150 0.05 1 0.25
212/720 150 0.05 1 0.5
213/720 150 0.05 1 1.0
214/720 150 0.05 1 1.25
215/720 150 0.05 1 1.5
216/720 150 0.05 2 0.25
217/720 150 0.05 2 0.5
218/720 150 0.05 2 1.0
219/720 150 0.05 2 1.25
220/720 150 0.05 2 1.5
221/720 150 0.05 3 0.25
222/720 150 0.05 3 0.5
223/720 150 0.05 3 1.0
224/720 150 0.05 3 1.25
225/720 150 0.05 3 1.5
226/720 150 0.05 5 0.25
227/720 150 0.05 5 0.5
228/720 150 0.05 5 1.0
229/720 150 0.05 5 1.25
230/720 150 0.05 5 1.5
231/720 150 0.05 8 0.25
232/720 150 0.05 8 0.5
233/720 150 0.05 8 1.0
234/720 150 0.05 8 1.25
235/720 150 0.05 8 1.5
236/720 150 0.05 10 0.25
237/720 150 0.05 10 0.5
238/720 150 0.05 10 1.0
239/720 150 0.05 10 1.25
240/720 150 0.05 10 1.5
241/720 200 0.005 1 0.25
242/720 200 0.005 1 0.5
243/720 200 0.005 1 1.0
244/720 200 0.005 1 1.25
245/720 200 0.005 1 1.5
246/720 200 0.005 2 0.25
247/720 200 0.005 2 0.5
248/720 200 0.005 2 1.0
249/720 200 0.005 2 1.25
250/720 200 0.005 2 1.5
251/720 200 0.005 3 0.25
252/720 200 0.005 3 0.5
253/720 200 0.005 3 1.0
254/720 200 0.005 3 1.25
255/720 200 0.005 3 1.5
256/720 200 0.005 5 0.25
257/720 200 0.005 5 0.5
258/720 200 0.005 5 1.0
259/720 200 0.005 5 1.25
260/720 200 0.005 5 1.5
261/720 200 0.005 8 0.25
262/720 200 0.005 8 0.5
263/720 200 0.005 8 1.0
264/720 200 0.005 8 1.25
265/720 200 0.005 8 1.5
266/720 200 0.005 10 0.25
267/720 200 0.005 10 0.5
268/720 200 0.005 10 1.0
269/720 200 0.005 10 1.25
270/720 200 0.005 10 1.5
271/720 200 0.01 1 0.25
272/720 200 0.01 1 0.5
273/720 200 0.01 1 1.0
274/720 200 0.01 1 1.25
275/720 200 0.01 1 1.5
276/720 200 0.01 2 0.25
277/720 200 0.01 2 0.5
278/720 200 0.01 2 1.0
279/720 200 0.01 2 1.25
280/720 200 0.01 2 1.5
281/720 200 0.01 3 0.25
282/720 200 0.01 3 0.5
283/720 200 0.01 3 1.0
284/720 200 0.01 3 1.25
285/720 200 0.01 3 1.5
286/720 200 0.01 5 0.25
287/720 200 0.01 5 0.5
288/720 200 0.01 5 1.0
289/720 200 0.01 5 1.25
290/720 200 0.01 5 1.5
291/720 200 0.01 8 0.25
292/720 200 0.01 8 0.5
293/720 200 0.01 8 1.0
294/720 200 0.01 8 1.25
295/720 200 0.01 8 1.5
296/720 200 0.01 10 0.25
297/720 200 0.01 10 0.5
298/720 200 0.01 10 1.0
299/720 200 0.01 10 1.25
300/720 200 0.01 10 1.5
301/720 200 0.03 1 0.25
302/720 200 0.03 1 0.5
303/720 200 0.03 1 1.0
304/720 200 0.03 1 1.25
305/720 200 0.03 1 1.5
306/720 200 0.03 2 0.25
307/720 200 0.03 2 0.5
308/720 200 0.03 2 1.0
309/720 200 0.03 2 1.25
310/720 200 0.03 2 1.5
311/720 200 0.03 3 0.25
312/720 200 0.03 3 0.5
313/720 200 0.03 3 1.0
314/720 200 0.03 3 1.25
315/720 200 0.03 3 1.5
316/720 200 0.03 5 0.25
317/720 200 0.03 5 0.5
318/720 200 0.03 5 1.0
319/720 200 0.03 5 1.25
320/720 200 0.03 5 1.5
321/720 200 0.03 8 0.25
322/720 200 0.03 8 0.5
323/720 200 0.03 8 1.0
324/720 200 0.03 8 1.25
325/720 200 0.03 8 1.5
326/720 200 0.03 10 0.25
327/720 200 0.03 10 0.5
328/720 200 0.03 10 1.0
329/720 200 0.03 10 1.25
330/720 200 0.03 10 1.5
331/720 200 0.05 1 0.25
332/720 200 0.05 1 0.5
333/720 200 0.05 1 1.0
334/720 200 0.05 1 1.25
335/720 200 0.05 1 1.5
336/720 200 0.05 2 0.25
337/720 200 0.05 2 0.5
338/720 200 0.05 2 1.0
339/720 200 0.05 2 1.25
340/720 200 0.05 2 1.5
341/720 200 0.05 3 0.25
342/720 200 0.05 3 0.5
343/720 200 0.05 3 1.0
344/720 200 0.05 3 1.25
345/720 200 0.05 3 1.5
346/720 200 0.05 5 0.25
347/720 200 0.05 5 0.5
348/720 200 0.05 5 1.0
349/720 200 0.05 5 1.25
350/720 200 0.05 5 1.5
351/720 200 0.05 8 0.25
352/720 200 0.05 8 0.5
353/720 200 0.05 8 1.0
354/720 200 0.05 8 1.25

355/720 200 0.05 8 1.5
356/720 200 0.05 10 0.25
357/720 200 0.05 10 0.5
358/720 200 0.05 10 1.0
359/720 200 0.05 10 1.25
360/720 200 0.05 10 1.5
361/720 250 0.005 1 0.25
362/720 250 0.005 1 0.5
363/720 250 0.005 1 1.0
364/720 250 0.005 1 1.25
365/720 250 0.005 1 1.5
366/720 250 0.005 2 0.25
367/720 250 0.005 2 0.5
368/720 250 0.005 2 1.0
369/720 250 0.005 2 1.25
370/720 250 0.005 2 1.5
371/720 250 0.005 3 0.25
372/720 250 0.005 3 0.5
373/720 250 0.005 3 1.0
374/720 250 0.005 3 1.25
375/720 250 0.005 3 1.5
376/720 250 0.005 5 0.25
377/720 250 0.005 5 0.5
378/720 250 0.005 5 1.0
379/720 250 0.005 5 1.25
380/720 250 0.005 5 1.5
381/720 250 0.005 8 0.25
382/720 250 0.005 8 0.5
383/720 250 0.005 8 1.0
384/720 250 0.005 8 1.25
385/720 250 0.005 8 1.5
386/720 250 0.005 10 0.25
387/720 250 0.005 10 0.5
388/720 250 0.005 10 1.0
389/720 250 0.005 10 1.25
390/720 250 0.005 10 1.5
391/720 250 0.01 1 0.25
392/720 250 0.01 1 0.5
393/720 250 0.01 1 1.0
394/720 250 0.01 1 1.25
395/720 250 0.01 1 1.5
396/720 250 0.01 2 0.25
397/720 250 0.01 2 0.5
398/720 250 0.01 2 1.0
399/720 250 0.01 2 1.25
400/720 250 0.01 2 1.5
401/720 250 0.01 3 0.25
402/720 250 0.01 3 0.5
403/720 250 0.01 3 1.0
404/720 250 0.01 3 1.25
405/720 250 0.01 3 1.5
406/720 250 0.01 5 0.25
407/720 250 0.01 5 0.5
408/720 250 0.01 5 1.0
409/720 250 0.01 5 1.25
410/720 250 0.01 5 1.5
411/720 250 0.01 8 0.25
412/720 250 0.01 8 0.5
413/720 250 0.01 8 1.0
414/720 250 0.01 8 1.25
415/720 250 0.01 8 1.5
416/720 250 0.01 10 0.25
417/720 250 0.01 10 0.5
418/720 250 0.01 10 1.0
419/720 250 0.01 10 1.25
420/720 250 0.01 10 1.5
421/720 250 0.03 1 0.25
422/720 250 0.03 1 0.5
423/720 250 0.03 1 1.0
424/720 250 0.03 1 1.25
425/720 250 0.03 1 1.5
426/720 250 0.03 2 0.25
427/720 250 0.03 2 0.5
428/720 250 0.03 2 1.0
429/720 250 0.03 2 1.25
430/720 250 0.03 2 1.5
431/720 250 0.03 3 0.25
432/720 250 0.03 3 0.5
433/720 250 0.03 3 1.0
434/720 250 0.03 3 1.25
435/720 250 0.03 3 1.5
436/720 250 0.03 5 0.25
437/720 250 0.03 5 0.5
438/720 250 0.03 5 1.0
439/720 250 0.03 5 1.25
440/720 250 0.03 5 1.5
441/720 250 0.03 8 0.25
442/720 250 0.03 8 0.5
443/720 250 0.03 8 1.0
444/720 250 0.03 8 1.25
445/720 250 0.03 8 1.5
446/720 250 0.03 10 0.25
447/720 250 0.03 10 0.5
448/720 250 0.03 10 1.0
449/720 250 0.03 10 1.25
450/720 250 0.03 10 1.5
451/720 250 0.05 1 0.25
452/720 250 0.05 1 0.5
453/720 250 0.05 1 1.0
454/720 250 0.05 1 1.25
455/720 250 0.05 1 1.5
456/720 250 0.05 2 0.25
457/720 250 0.05 2 0.5
458/720 250 0.05 2 1.0
459/720 250 0.05 2 1.25
460/720 250 0.05 2 1.5
461/720 250 0.05 3 0.25
462/720 250 0.05 3 0.5
463/720 250 0.05 3 1.0
464/720 250 0.05 3 1.25
465/720 250 0.05 3 1.5
466/720 250 0.05 5 0.25
467/720 250 0.05 5 0.5
468/720 250 0.05 5 1.0
469/720 250 0.05 5 1.25
470/720 250 0.05 5 1.5
471/720 250 0.05 8 0.25
472/720 250 0.05 8 0.5
473/720 250 0.05 8 1.0
474/720 250 0.05 8 1.25
475/720 250 0.05 8 1.5
476/720 250 0.05 10 0.25
477/720 250 0.05 10 0.5
478/720 250 0.05 10 1.0
479/720 250 0.05 10 1.25
480/720 250 0.05 10 1.5
481/720 300 0.005 1 0.25
482/720 300 0.005 1 0.5
483/720 300 0.005 1 1.0
484/720 300 0.005 1 1.25
485/720 300 0.005 1 1.5
486/720 300 0.005 2 0.25
487/720 300 0.005 2 0.5
488/720 300 0.005 2 1.0
489/720 300 0.005 2 1.25
490/720 300 0.005 2 1.5
491/720 300 0.005 3 0.25
492/720 300 0.005 3 0.5
493/720 300 0.005 3 1.0
494/720 300 0.005 3 1.25
495/720 300 0.005 3 1.5
496/720 300 0.005 5 0.25
497/720 300 0.005 5 0.5
498/720 300 0.005 5 1.0
499/720 300 0.005 5 1.25
500/720 300 0.005 5 1.5
501/720 300 0.005 8 0.25
502/720 300 0.005 8 0.5
503/720 300 0.005 8 1.0
504/720 300 0.005 8 1.25
505/720 300 0.005 8 1.5
506/720 300 0.005 10 0.25
507/720 300 0.005 10 0.5
508/720 300 0.005 10 1.0
509/720 300 0.005 10 1.25
510/720 300 0.005 10 1.5
511/720 300 0.01 1 0.25
512/720 300 0.01 1 0.5
513/720 300 0.01 1 1.0
514/720 300 0.01 1 1.25
515/720 300 0.01 1 1.5
516/720 300 0.01 2 0.25
517/720 300 0.01 2 0.5
518/720 300 0.01 2 1.0
519/720 300 0.01 2 1.25
520/720 300 0.01 2 1.5
521/720 300 0.01 3 0.25
522/720 300 0.01 3 0.5
523/720 300 0.01 3 1.0
524/720 300 0.01 3 1.25
525/720 300 0.01 3 1.5
526/720 300 0.01 5 0.25
527/720 300 0.01 5 0.5
528/720 300 0.01 5 1.0
529/720 300 0.01 5 1.25
530/720 300 0.01 5 1.5
531/720 300 0.01 8 0.25
532/720 300 0.01 8 0.5
533/720 300 0.01 8 1.0
534/720 300 0.01 8 1.25
535/720 300 0.01 8 1.5
536/720 300 0.01 10 0.25
537/720 300 0.01 10 0.5
538/720 300 0.01 10 1.0
539/720 300 0.01 10 1.25
540/720 300 0.01 10 1.5
541/720 300 0.03 1 0.25
542/720 300 0.03 1 0.5
543/720 300 0.03 1 1.0
544/720 300 0.03 1 1.25
545/720 300 0.03 1 1.5
546/720 300 0.03 2 0.25
547/720 300 0.03 2 0.5
548/720 300 0.03 2 1.0
549/720 300 0.03 2 1.25
550/720 300 0.03 2 1.5
551/720 300 0.03 3 0.25
552/720 300 0.03 3 0.5
553/720 300 0.03 3 1.0
554/720 300 0.03 3 1.25
555/720 300 0.03 3 1.5
556/720 300 0.03 5 0.25
557/720 300 0.03 5 0.5
558/720 300 0.03 5 1.0
559/720 300 0.03 5 1.25
560/720 300 0.03 5 1.5
561/720 300 0.03 8 0.25
562/720 300 0.03 8 0.5
563/720 300 0.03 8 1.0
564/720 300 0.03 8 1.25
565/720 300 0.03 8 1.5
566/720 300 0.03 10 0.25
567/720 300 0.03 10 0.5
568/720 300 0.03 10 1.0
569/720 300 0.03 10 1.25
570/720 300 0.03 10 1.5
571/720 300 0.05 1 0.25
572/720 300 0.05 1 0.5
573/720 300 0.05 1 1.0
574/720 300 0.05 1 1.25
575/720 300 0.05 1 1.5
576/720 300 0.05 2 0.25
577/720 300 0.05 2 0.5
578/720 300 0.05 2 1.0
579/720 300 0.05 2 1.25
580/720 300 0.05 2 1.5
581/720 300 0.05 3 0.25
582/720 300 0.05 3 0.5
583/720 300 0.05 3 1.0
584/720 300 0.05 3 1.25
585/720 300 0.05 3 1.5
586/720 300 0.05 5 0.25
587/720 300 0.05 5 0.5
588/720 300 0.05 5 1.0
589/720 300 0.05 5 1.25
590/720 300 0.05 5 1.5
591/720 300 0.05 8 0.25
592/720 300 0.05 8 0.5
593/720 300 0.05 8 1.0
594/720 300 0.05 8 1.25
595/720 300 0.05 8 1.5
596/720 300 0.05 10 0.25
597/720 300 0.05 10 0.5
598/720 300 0.05 10 1.0
599/720 300 0.05 10 1.25
600/720 300 0.05 10 1.5
601/720 350 0.005 1 0.25
602/720 350 0.005 1 0.5
603/720 350 0.005 1 1.0
604/720 350 0.005 1 1.25
605/720 350 0.005 1 1.5
606/720 350 0.005 2 0.25
607/720 350 0.005 2 0.5
608/720 350 0.005 2 1.0
609/720 350 0.005 2 1.25
610/720 350 0.005 2 1.5
611/720 350 0.005 3 0.25
612/720 350 0.005 3 0.5
613/720 350 0.005 3 1.0
614/720 350 0.005 3 1.25
615/720 350 0.005 3 1.5
616/720 350 0.005 5 0.25
617/720 350 0.005 5 0.5
618/720 350 0.005 5 1.0
619/720 350 0.005 5 1.25
620/720 350 0.005 5 1.5
621/720 350 0.005 8 0.25
622/720 350 0.005 8 0.5
623/720 350 0.005 8 1.0
624/720 350 0.005 8 1.25
625/720 350 0.005 8 1.5
626/720 350 0.005 10 0.25
627/720 350 0.005 10 0.5
628/720 350 0.005 10 1.0
629/720 350 0.005 10 1.25
630/720 350 0.005 10 1.5
631/720 350 0.01 1 0.25
632/720 350 0.01 1 0.5
633/720 350 0.01 1 1.0
634/720 350 0.01 1 1.25
635/720 350 0.01 1 1.5
636/720 350 0.01 2 0.25
637/720 350 0.01 2 0.5
638/720 350 0.01 2 1.0
639/720 350 0.01 2 1.25
640/720 350 0.01 2 1.5
641/720 350 0.01 3 0.25
642/720 350 0.01 3 0.5
643/720 350 0.01 3 1.0
644/720 350 0.01 3 1.25
645/720 350 0.01 3 1.5
646/720 350 0.01 5 0.25
647/720 350 0.01 5 0.5
648/720 350 0.01 5 1.0
649/720 350 0.01 5 1.25
650/720 350 0.01 5 1.5
651/720 350 0.01 8 0.25
652/720 350 0.01 8 0.5
653/720 350 0.01 8 1.0
654/720 350 0.01 8 1.25
655/720 350 0.01 8 1.5
656/720 350 0.01 10 0.25
657/720 350 0.01 10 0.5
658/720 350 0.01 10 1.0
659/720 350 0.01 10 1.25
660/720 350 0.01 10 1.5
661/720 350 0.03 1 0.25
662/720 350 0.03 1 0.5
663/720 350 0.03 1 1.0
664/720 350 0.03 1 1.25
665/720 350 0.03 1 1.5
666/720 350 0.03 2 0.25
667/720 350 0.03 2 0.5
668/720 350 0.03 2 1.0
669/720 350 0.03 2 1.25
670/720 350 0.03 2 1.5
671/720 350 0.03 3 0.25
672/720 350 0.03 3 0.5
673/720 350 0.03 3 1.0
674/720 350 0.03 3 1.25
675/720 350 0.03 3 1.5
676/720 350 0.03 5 0.25
677/720 350 0.03 5 0.5
678/720 350 0.03 5 1.0
679/720 350 0.03 5 1.25
680/720 350 0.03 5 1.5
681/720 350 0.03 8 0.25
682/720 350 0.03 8 0.5
683/720 350 0.03 8 1.0
684/720 350 0.03 8 1.25
685/720 350 0.03 8 1.5
686/720 350 0.03 10 0.25
687/720 350 0.03 10 0.5
688/720 350 0.03 10 1.0
689/720 350 0.03 10 1.25
690/720 350 0.03 10 1.5
691/720 350 0.05 1 0.25
692/720 350 0.05 1 0.5
693/720 350 0.05 1 1.0
694/720 350 0.05 1 1.25
695/720 350 0.05 1 1.5
696/720 350 0.05 2 0.25
697/720 350 0.05 2 0.5
698/720 350 0.05 2 1.0

699/720 350 0.05 2 1.25
700/720 350 0.05 2 1.5
701/720 350 0.05 3 0.25
702/720 350 0.05 3 0.5
703/720 350 0.05 3 1.0
704/720 350 0.05 3 1.25
705/720 350 0.05 3 1.5
706/720 350 0.05 5 0.25
707/720 350 0.05 5 0.5
708/720 350 0.05 5 1.0
709/720 350 0.05 5 1.25
710/720 350 0.05 5 1.5
711/720 350 0.05 8 0.25
712/720 350 0.05 8 0.5
713/720 350 0.05 8 1.0
714/720 350 0.05 8 1.25
715/720 350 0.05 8 1.5
716/720 350 0.05 10 0.25
717/720 350 0.05 10 0.5
718/720 350 0.05 10 1.0
719/720 350 0.05 10 1.25
720/720 350 0.05 10 1.5
CPU times: total: 18min 18s
Wall time: 15h 22min 28s

In [18]:
data = [prec_met, map_met]
data = pd.DataFrame(data, index =['Precision@k', 'MAP@k'])
data = data.T

In [19]:
data.sort_values('Precision@k', ascending=False)

                       Precision@k     MAP@k
als_spark_300_0.05_10     0.286907  0.220063
als_spark_350_0.05_10     0.286802  0.219798
als_spark_350_0.05_8      0.286489  0.219002
als_spark_350_0.05_5      0.285968  0.218560
als_spark_300_0.03_8      0.285133  0.219111
...                            ...       ...
als_spark_50_0.005_2      0.180386  0.118409
als_spark_50_0.01_1       0.142514  0.083462
als_spark_50_0.005_1      0.142201  0.083295
als_spark_50_0.03_1       0.140219  0.083685
als_spark_50_0.05_1       0.136463  0.084017

[144 rows x 2 columns]

In [20]:
data.sort_values('MAP@k', ascending=False)

                       Precision@k     MAP@k
als_spark_300_0.05_10     0.286907  0.220063
als_spark_350_0.05_10     0.286802  0.219798
als_spark_300_0.03_10     0.284298  0.219298
als_spark_300_0.03_8      0.285133  0.219111
als_spark_350_0.05_8      0.286489  0.219002
...                            ...       ...
als_spark_50_0.005_2      0.180386  0.118409
als_spark_50_0.05_1       0.136463  0.084017
als_spark_50_0.03_1       0.140219  0.083685
als_spark_50_0.01_1       0.142514  0.083462
als_spark_50_0.005_1      0.142201  0.083295

[144 rows x 2 columns]

In [21]:
# Лучшие параметры по метрике Precision@5
data[data['Precision@k'] == data['Precision@k'].max()]

                       Precision@k     MAP@k
als_spark_300_0.05_10     0.286907  0.220063

In [22]:
# Лучшие параметры по метрике MAP@5
data[data['MAP@k'] == data['MAP@k'].max()]

                       Precision@k     MAP@k
als_spark_300_0.05_10     0.286907  0.220063

Проведем дополнительный перебор параметров, т.к. некоторые приняли максимальные указанные их значения в списках.

In [16]:
# Словари метрик
prec_met = dict()
map_met = dict()

# Списки гиперпараметров для моделей
factors = [300,]
reg_st = [0.01, 0.25, 0.05,]
alpha = [0.05, 0.1, 0.05, 0.5, 1.0, 1.5]
iterations = [15, 20] # 20 max, 25 вылетает

In [17]:
%%time
result, prec_met, map_met = als_spark(prec_met, map_met, result, spark_data_train, factors, reg_st, iterations, alpha, N=5)

1/36 300 0.01 15 0.05
2/36 300 0.01 15 0.1
3/36 300 0.01 15 0.05
4/36 300 0.01 15 0.5
5/36 300 0.01 15 1.0
6/36 300 0.01 15 1.5
7/36 300 0.01 20 0.05
8/36 300 0.01 20 0.1
9/36 300 0.01 20 0.05
10/36 300 0.01 20 0.5
11/36 300 0.01 20 1.0
12/36 300 0.01 20 1.5
13/36 300 0.25 15 0.05
14/36 300 0.25 15 0.1
15/36 300 0.25 15 0.05
16/36 300 0.25 15 0.5
17/36 300 0.25 15 1.0
18/36 300 0.25 15 1.5
19/36 300 0.25 20 0.05
20/36 300 0.25 20 0.1
21/36 300 0.25 20 0.05
22/36 300 0.25 20 0.5
23/36 300 0.25 20 1.0
24/36 300 0.25 20 1.5
25/36 300 0.05 15 0.05
26/36 300 0.05 15 0.1
27/36 300 0.05 15 0.05
28/36 300 0.05 15 0.5
29/36 300 0.05 15 1.0
30/36 300 0.05 15 1.5
31/36 300 0.05 20 0.05
32/36 300 0.05 20 0.1
33/36 300 0.05 20 0.05
34/36 300 0.05 20 0.5
35/36 300 0.05 20 1.0
36/36 300 0.05 20 1.5
CPU times: total: 56.2 s
Wall time: 4h 11min 14s

In [19]:
data = [prec_met, map_met]
data = pd.DataFrame(data, index =['Precision@k', 'MAP@k'])
data = data.T

In [20]:
data.sort_values('Precision@k', ascending=False)

                            Precision@k     MAP@k
als_spark_300_0.01_0.05_20     0.295149  0.236020
als_spark_300_0.01_0.05_15     0.295044  0.236039
als_spark_300_0.01_0.1_20      0.294627  0.233865
als_spark_300_0.01_0.1_15      0.294418  0.233692
als_spark_300_0.05_0.05_20     0.291706  0.232495
als_spark_300_0.05_0.05_15     0.291601  0.232323
als_spark_300_0.05_0.1_20      0.290037  0.231297
als_spark_300_0.05_0.5_20      0.289411  0.227232
als_spark_300_0.05_0.1_15      0.289098  0.230696
als_spark_300_0.01_0.5_15      0.288889  0.224448
als_spark_300_0.01_0.5_20      0.288576  0.223996
als_spark_300_0.05_0.5_15      0.288576  0.226648
als_spark_300_0.05_1.0_15      0.287428  0.222911
als_spark_300_0.05_1.0_20      0.287324  0.223222
als_spark_300_0.05_1.5_20      0.285550  0.218997
als_spark_300_0.05_1.5_15      0.285342  0.219115
als_spark_300_0.01_1.0_20      0.283255  0.218658
als_spark_300_0.01_1.0_15      0.282838  0.217877
als_spark_300_0.01_1.5_20      0.278352  0.213111
als_spark_300_0.01_1.5_15      0.278352  0.213257
als_spark_300_0.25_1.5_15      0.192488  0.131400
als_spark_300_0.25_1.5_20      0.192488  0.131495
als_spark_300_0.25_1.0_20      0.174961  0.117366
als_spark_300_0.25_1.0_15      0.174961  0.117395
als_spark_300_0.25_0.5_20      0.157851  0.103545
als_spark_300_0.25_0.5_15      0.157746  0.103486
als_spark_300_0.25_0.1_20      0.146375  0.095684
als_spark_300_0.25_0.1_15      0.146375  0.095684
als_spark_300_0.25_0.05_15     0.144497  0.095296
als_spark_300_0.25_0.05_20     0.144392  0.095267

In [21]:
data.sort_values('MAP@k', ascending=False)

                            Precision@k     MAP@k
als_spark_300_0.01_0.05_15     0.295044  0.236039
als_spark_300_0.01_0.05_20     0.295149  0.236020
als_spark_300_0.01_0.1_20      0.294627  0.233865
als_spark_300_0.01_0.1_15      0.294418  0.233692
als_spark_300_0.05_0.05_20     0.291706  0.232495
als_spark_300_0.05_0.05_15     0.291601  0.232323
als_spark_300_0.05_0.1_20      0.290037  0.231297
als_spark_300_0.05_0.1_15      0.289098  0.230696
als_spark_300_0.05_0.5_20      0.289411  0.227232
als_spark_300_0.05_0.5_15      0.288576  0.226648
als_spark_300_0.01_0.5_15      0.288889  0.224448
als_spark_300_0.01_0.5_20      0.288576  0.223996
als_spark_300_0.05_1.0_20      0.287324  0.223222
als_spark_300_0.05_1.0_15      0.287428  0.222911
als_spark_300_0.05_1.5_15      0.285342  0.219115
als_spark_300_0.05_1.5_20      0.285550  0.218997
als_spark_300_0.01_1.0_20      0.283255  0.218658
als_spark_300_0.01_1.0_15      0.282838  0.217877
als_spark_300_0.01_1.5_15      0.278352  0.213257
als_spark_300_0.01_1.5_20      0.278352  0.213111
als_spark_300_0.25_1.5_20      0.192488  0.131495
als_spark_300_0.25_1.5_15      0.192488  0.131400
als_spark_300_0.25_1.0_15      0.174961  0.117395
als_spark_300_0.25_1.0_20      0.174961  0.117366
als_spark_300_0.25_0.5_20      0.157851  0.103545
als_spark_300_0.25_0.5_15      0.157746  0.103486
als_spark_300_0.25_0.1_20      0.146375  0.095684
als_spark_300_0.25_0.1_15      0.146375  0.095684
als_spark_300_0.25_0.05_15     0.144497  0.095296
als_spark_300_0.25_0.05_20     0.144392  0.095267

In [22]:
# Лучшие параметры по метрике Precision@5
data[data['Precision@k'] == data['Precision@k'].max()]

                            Precision@k    MAP@k
als_spark_300_0.01_0.05_20     0.295149  0.23602

In [23]:
# Лучшие параметры по метрике MAP@5
data[data['MAP@k'] == data['MAP@k'].max()]

                            Precision@k     MAP@k
als_spark_300_0.01_0.05_15     0.295044  0.236039

In [24]:
session.stop()

### Сравним метрики с ALS моделью с лучшими найденными параметрами

In [10]:
def get_recommendations(user, model, sparse_user_item, N=5):
    res = [id_to_itemid[rec] for rec in 
                    model.recommend(userid=userid_to_id[user], # можно вставить несколько пользователей
                                    user_items=sparse_user_item[userid_to_id[user]],   # на вход user-item matrix
                                    N=N, 
                                    filter_already_liked_items=False, 
                                    filter_items=[itemid_to_id[999999]], 
                                    recalculate_user=True)[0]] # recalculate_user=True это для перерасчета для новых users
    return res

In [13]:
%%time
bm25_user_item_matrix = bm25_weight(user_item_matrix.T).T.tocsr()

model = AlternatingLeastSquares(factors=350, 
                regularization=0.05,
                iterations=1,
                calculate_training_loss=True, 
                random_state=42)

model.fit(bm25_user_item_matrix, show_progress=False)

CPU times: total: 8.19 s
Wall time: 851 ms

In [16]:
test_users = result.shape[0]
new_test_users = len(set(data_test['user_id']) - set(data_train['user_id']))

print('В тестовом дата сете {} юзеров'.format(test_users))
print('В тестовом дата сете {} новых юзеров'.format(new_test_users))

В тестовом дата сете 1919 юзеров
В тестовом дата сете 2 новых юзеров

In [17]:
# уберем пользователей, которых нет в трейне
new_test_users = set(data_test['user_id']) - set(data_train['user_id'])
result = result[~result['user_id'].isin(new_test_users)]

In [20]:
result['als_bm25_T'] = result['user_id'].map(lambda x: get_recommendations(x, model, sparse_user_item, 5))
print('Precision@k: ', result.apply(lambda row: precision_at_k(row[f'als_bm25_T'], row['actual']), axis=1).mean())
print('MAP@k: ', result.apply(lambda row: ap_k(row[f'als_bm25_T'], row['actual']), axis=1).mean())

Precision@k:  0.2372456964006229
MAP@k:  0.17222396105025153

**Выводы:** модель ALS Spark показала значительно лучшие результаты